- name: Deploy Stateful Services to Kubernetes
  hosts: localhost
  vars:
    ansible_python_interpreter: /home/kirya/FinSight-ansible/venv/bin/python
  gather_facts: false
  roles:
    - postgresql_ha_deploy
    - kafka_deploy
