---
- name: Deploy Kafka via Helm with templated values
  community.kubernetes.helm:
    name: kafka
    chart_ref: bitnami/kafka
    release_namespace: kafka
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig }}"
    chart_version: "32.2.16"  # актуальная версия на июнь 2025
    state: present

- name: Wait for Kafka pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: stateful-services
    label_selectors:
      - app.kubernetes.io/name=kafka
    kubeconfig: "{{ kubeconfig }}"
  register: kafka_pods
  until: kafka_pods.resources | length > 0 and (kafka_pods.resources | map(attribute='status.phase') | select('equalto', 'Running') | list | length) == kafka_pods.resources | length
  retries: 6
  delay: 10

- name: Show Kafka pod names and status
  debug:
    msg: "{{ kafka_pods.resources | map(attribute='metadata.name') | list }}"
