- name: Deploy postgresql-ha Helm chart
  community.kubernetes.helm:
    name: postgresql-ha
    chart_ref: bitnami/postgresql-ha
    release_namespace: postgres
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    kubeconfig: "{{ kubeconfig }}"
    version: "16.0.14"
    state: present

- name: Get current Pods in postgres namespace
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: postgres
    kubeconfig: "{{ kubeconfig }}"
  register: pod_info

- name: Print pod names
  debug:
    msg: "{{ pod_info.resources | map(attribute='metadata.name') | list }}"
